using Microsoft.CodeAnalysis;

namespace Minos.AotSmoke.Tests;

/// <summary>
/// The public entry points both packages declare in their PublicAPI files: every public constructor and method, with
/// its signature exactly as RS0016 prints it, after applying the <c>*REMOVED*</c> lines.
/// </summary>
/// <remarks>
/// <para>A PublicAPI line that is not an entry point is excluded with the reason <see cref="ExclusionReason"/> gives:</para>
/// <list type="bullet">
/// <item>Type declarations: a type is not called; its constructors and methods are its entry points.</item>
/// <item>Property and indexer accessors, fields, constants and enum members: they are data, read or written through
/// the entry points that take or return them, and are covered through their types.</item>
/// <item>Operators, user-defined conversions included: they are syntax over an entry point, such as <c>==</c> over a
/// declared <c>Equals(T)</c>, or over a factory such as <c>DecisionContent.FromString</c>.</item>
/// <item><c>override</c>s of <see cref="object"/>'s <c>Equals(object)</c>, <c>GetHashCode()</c> and
/// <c>ToString()</c>: they are the runtime's contract, not this library's API.</item>
/// <item>The members the compiler generates for a record, such as <c>&lt;Clone&gt;$</c>, <c>Deconstruct</c>,
/// <c>PrintMembers</c> and <c>Equals(T? other)</c>. A member is recognised as generated by the
/// <c>[CompilerGenerated]</c> attribute the compiler puts on it in the package's assembly, never by its name, so a
/// record member its author wrote, such as a hand-written <c>Deconstruct</c> or <c>Equals(T? other)</c>, counts. A
/// struct's <c>Equals(T other)</c> is the one its author wrote for <see cref="IEquatable{T}"/>, and it counts.</item>
/// </list>
/// <para>Interface members, such as <c>IDecisionClient</c>'s, and extension methods, such as <c>DecisionClientExtensions</c>', are entry points like any other.</para>
/// </remarks>
internal static class PublicApi
{
    private const string Arrow = " -> ";
    private const string RemovedPrefix = "*REMOVED*";

    private static readonly string[][] Packages =
    [
        ["src/Minos.NET/PublicAPI.Shipped.txt", "src/Minos.NET/PublicAPI.Unshipped.txt"],
        [
            "src/Minos.NET.DependencyInjection/PublicAPI.Shipped.txt",
            "src/Minos.NET.DependencyInjection/PublicAPI.Unshipped.txt",
        ],
    ];

    private const string CompilerGeneratedAttribute = "System.Runtime.CompilerServices.CompilerGeneratedAttribute";

    private static readonly string[] PackageNames = ["Minos.NET", "Minos.NET.DependencyInjection"];

    private static readonly string[] ObjectMembers = ["Equals(object? obj)", "GetHashCode()", "ToString()"];

    /// <summary>Every line both packages declare, after applying the <c>*REMOVED*</c> lines.</summary>
    public static List<string> Lines { get; } = ReadLines();

    /// <summary>The PublicAPI lines of the record members the compiler generated in both packages.</summary>
    // Initialised before EntryPoints, which reads it.
    private static HashSet<string> GeneratedRecordMembers { get; } = FindGeneratedRecordMembers(
        PackageNames.Select(name => FindAssembly(SampleCompilation.Smoke.Compilation, name)));

    /// <summary>The entry points: every line <see cref="ExclusionReason"/> keeps.</summary>
    public static List<string> EntryPoints { get; } = [.. Lines.Where(line => ExclusionReason(line) is null)];

    /// <summary>Why <paramref name="line"/> is not an entry point, or <see langword="null"/> when it is one.</summary>
    public static string? ExclusionReason(string line) => ExclusionReason(line, GeneratedRecordMembers);

    /// <summary>Why <paramref name="line"/> is not an entry point, given the PublicAPI lines of the record members the
    /// compiler generated, or <see langword="null"/> when it is one.</summary>
    internal static string? ExclusionReason(string line, IReadOnlySet<string> generatedRecordMembers)
    {
        var arrow = line.IndexOf(Arrow, StringComparison.Ordinal);
        if (arrow < 0)
        {
            return "a type declaration; its constructors and methods are its entry points";
        }

        var declaration = StripModifiers(line[..arrow], out var modifiers);
        if (modifiers.Contains("const", StringComparer.Ordinal))
        {
            return "a constant, covered through its type";
        }

        if (declaration.EndsWith(".get", StringComparison.Ordinal)
            || declaration.EndsWith(".set", StringComparison.Ordinal)
            || declaration.EndsWith(".init", StringComparison.Ordinal))
        {
            return "a property or indexer accessor, covered through its type";
        }

        var open = declaration.IndexOf('(', StringComparison.Ordinal);
        if (open < 0)
        {
            return "a field or enum member, covered through its type";
        }

        if (declaration[..open].Contains("operator ", StringComparison.Ordinal))
        {
            return "an operator or a user-defined conversion, syntax over the entry points it calls";
        }

        var (_, member) = Split(declaration[..open]);

        var signature = member + declaration[open..];
        if (modifiers.Contains("override", StringComparer.Ordinal) && ObjectMembers.Contains(signature, StringComparer.Ordinal))
        {
            return "an override of an object member";
        }

        if (generatedRecordMembers.Contains(line))
        {
            return "a member the compiler generates for a record";
        }

        return null;
    }

    /// <summary>The PublicAPI lines, as <see cref="ApiSignature"/> prints them, of the public and protected methods of
    /// a record in <paramref name="assemblies"/> that carry <c>[CompilerGenerated]</c>, which the compiler puts on every
    /// record member it synthesizes.</summary>
    internal static HashSet<string> FindGeneratedRecordMembers(IEnumerable<IAssemblySymbol> assemblies)
        => assemblies
            .SelectMany(assembly => PublicTypes(assembly.GlobalNamespace))
            .Where(type => type.IsRecord)
            .SelectMany(type => type.GetMembers().OfType<IMethodSymbol>())
            .Where(method => method.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal
                && method.GetAttributes().Any(attribute => string.Equals(attribute.AttributeClass?.ToDisplayString(), CompilerGeneratedAttribute, StringComparison.Ordinal)))
            .Select(ApiSignature.Of)
            .ToHashSet(StringComparer.Ordinal);

    private static IAssemblySymbol FindAssembly(Compilation compilation, string name)
        => compilation.References
            .Select(compilation.GetAssemblyOrModuleSymbol)
            .OfType<IAssemblySymbol>()
            .First(assembly => string.Equals(assembly.Name, name, StringComparison.Ordinal));

    private static IEnumerable<INamedTypeSymbol> PublicTypes(INamespaceSymbol ns)
        => ns.GetNamespaceMembers().SelectMany(PublicTypes)
            .Concat(ns.GetTypeMembers().SelectMany(PublicTypes));

    private static IEnumerable<INamedTypeSymbol> PublicTypes(INamedTypeSymbol type)
        => type.DeclaredAccessibility != Accessibility.Public
            ? []
            : type.GetTypeMembers().SelectMany(PublicTypes).Prepend(type);

    private static List<string> ReadLines()
    {
        var lines = new List<string>();
        foreach (var files in Packages)
        {
            lines.AddRange(ReadPackage(files));
        }

        return lines;
    }

    // One package's lines, Shipped and Unshipped together, so an Unshipped *REMOVED* line removes its Shipped line.
    private static List<string> ReadPackage(string[] files)
    {
        var package = files
            .SelectMany(file => File.ReadAllLines(Path.Combine(Repository.Root, file)))
            .Select(line => line.Trim())
            .Where(line => line.Length > 0 && !line.StartsWith("#nullable", StringComparison.Ordinal))
            .ToList();
        var removed = package
            .Where(line => line.StartsWith(RemovedPrefix, StringComparison.Ordinal))
            .Select(line => line[RemovedPrefix.Length..])
            .ToHashSet(StringComparer.Ordinal);
        return [.. package.Where(line => !line.StartsWith(RemovedPrefix, StringComparison.Ordinal) && !removed.Contains(line))];
    }

    // Leading modifiers, such as "static", "abstract" or "override", come before the qualified name and are lower case.
    private static string StripModifiers(string text, out List<string> modifiers)
    {
        modifiers = [];
        while (true)
        {
            var space = text.IndexOf(' ', StringComparison.Ordinal);
            var dot = text.IndexOf('.', StringComparison.Ordinal);
            var paren = text.IndexOf('(', StringComparison.Ordinal);
            if (space <= 0 || (dot >= 0 && dot < space) || (paren >= 0 && paren < space) || !IsLowerCaseWord(text[..space]))
            {
                return text;
            }

            modifiers.Add(text[..space]);
            text = text[(space + 1)..];
        }
    }

    private static bool IsLowerCaseWord(string word)
    {
        foreach (var c in word)
        {
            if (!char.IsAsciiLetterLower(c))
            {
                return false;
            }
        }

        return true;
    }

    // Splits "Namespace.Type<T>.Member" at the last '.' outside angle brackets, so "<Clone>$" and generic
    // containing types such as "Choice<T>" stay whole.
    private static (string ContainingType, string Member) Split(string qualified)
    {
        var depth = 0;
        var split = -1;
        for (var i = 0; i < qualified.Length; i++)
        {
            switch (qualified[i])
            {
                case '<':
                    depth++;
                    break;
                case '>':
                    depth--;
                    break;
                case '.' when depth == 0:
                    split = i;
                    break;
            }
        }

        return (qualified[..split], qualified[(split + 1)..]);
    }
}
